export const strings = {
    aboutUs: "Про нас",
    courses: "Курсы",
    login: "Войти",
    loginDescription: "С возвращением в Tañda. Войдите, используя свой телефон и пароль",
    register: "Регистрация",
    registerDescription: "Заполните регистрационные данные. Это займет пару минут. Все, что вам нужно, это номер телефона",
    yourAccountSecure: "Мы серьезно относимся к вопросам конфиденциальности. Вы можете быть уверены, что ваши личные данные надежно защищены.",
    phoneNumber: "Номер телефона",
    phoneNotConfirmed: "Номер еще не подтвержден",
    password: "Пароль",
    loginToYourAccount: "Войдите в свой аккаунт",
    role: "Роль",
    title: "Название",
    description: "Детали",
    type: "Тип",
    resources: "Материалы",
    sendCode: "Отправить код",
    firstName: "Имя",
    lastName: "Фамилия",
    code: "Код",
    forgotPassword: "Забыли пароль?",
    noAccount: "Нет учетной записи?",
    confirm: "Подтверждить",
    resetPassword: "Сбросить пароль",
    chooseImage: "Выбрать изображение",
    delete: "Удалить",
    save: "Сохранить",
    logOut: "Выйти",
    invalidPhoneNumber: "Введите действующий номер телефона",
    invalidPassword: "Введите надежный пароль",
    fullName: "Полное имя",
    status: "Статус",
    joinedAt: "Присоединился в",
    activate: "Активировать",
    archive: "Архивировать",
    addMember: "Добавить участника",
    members: "Участники",
    lessons: "Уроки",
    addLesson: "Добавить урок",
    lesson: "Урок",
    assignment: "Задание",
    exam: "Экзамен"
};
