export const authConstants = {
    REGISTER: "REGISTER",
    LOGIN: "LOGIN",
    RESEND_EMAIL: "RESEND_EMAIL",
    VERIFY_EMAIL: "VERITY_EMAIL",
    BECOME_PARTNER: "BECOME_PARTNER",
    GET_BECOME_PARTNER_REQUESTS: "GET_BECOME_PARTNER_REQUESTS",
    ACCEPT_BECOME_PARTNER_REQUEST: "ACCEPT_BECOME_PARTNER_REQUEST",
    DELETE_BECOME_PARTNER_REQUEST: "DELETE_BECOME_PARTNER_REQUEST",
    REQUEST_RESET_CODE: "REQUEST_RESET_CODE",
    SUBMIT_RESET_CODE: "SUBMIT_RESET_CODE",
    CHANGE_PASSWORD: "CHANGE_PASSWORD",
    LOGOUT: "LOGOUT",
};
