export const branchConstants = {
    GET_BRANCHES: "GET_BRANCHES",
    GET_MY_BRANCHES: "GET_MY_BRANCHES",
    GET_BRANCH: "GET_BRANCH",
    UPDATE_BRANCH: "UPDATE_BRANCH",
    DELETE_BRANCH: "DELETE_BRANCH",
}