export const schoolConstants = {
    GET_SCHOOLS: "GET_SCHOOLS",
    GET_MY_SCHOOLS: "GET_MY_SCHOOL",
    GET_SCHOOL: "GET_SCHOOL",
    CREATE_SCHOOL: "CREATE_SCHOOL",
    UPDATE_SCHOOL: "UPDATE_SCHOOL",
    DELETE_SCHOOL: "DELETE_SCHOOL",
}