export const authConstants = {
    REGISTER: "REGISTER",
    LOGIN: "LOGIN",
    RESEND_EMAIL: "RESEND_EMAIL",
    VERIFY_EMAIL: "VERITY_EMAIL",
    BECOME_PARTNER: "BECOME_PARTNER",
    REQUEST_RESET_CODE: "REQUEST_RESET_CODE",
    SUBMIT_RESET_CODE: "SUBMIT_RESET_CODE",
    CHANGE_PASSWORD: "CHANGE_PASSWORD",
    LOGOUT: "LOGOUT",
};
